# fly.toml app configuration file generated for polished-breeze-5688 on 2023-10-28T13:36:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "polished-breeze-5688"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
