name: Recommendoor
description: Recommendoor indexer
networks:
  - id: 114 # coston2
    start_block: 6680369
    rpc_config:
      url: https://coston2-api.flare.network/ext/C/rpc
    contracts:
      - name: Recommendoor
        address: "0xe36b6801d5F5248f4bDB239b6abC340EdBd48c9D"
        handler: ./src/EventHandlers.ts
        abi_file_path: ./abi/Recommendoor.json
        events:
          - event: "InteractData(address user, string ipfsHash, string action)"
            requiredEntities:
              - name: InteractData
          - event: "UploadData(address user, string ipfsHash, string channel)"
            requiredEntities:
              - name: UploadData
